### ISSUE TITLE
security concerns on Google Chrome

### ISSUE THREAD

**Issue by SimonEnsemble** [pro-panda/parchment#2]
hi. another odd phenomena with this theme on Github pages (my page [here](https://simonensemble.github.io/)) is that Google Chrome states "this page is trying to load scripts from unauthorized souces". Do you know why it could be warning that?

**Comment by pro-panda** [comment]
Thanks for reporting. Will see this over the weekend

**Comment by rhl-bthr** [comment]
@SimonEnsemble, thanks for reporting.

This warning usually appears when you are loading javascript code from sources over an HTTP connection instead of an HTTPS

I went through the original code and didn't observe any such issues. I went through your website and got this,
```
Mixed Content: The page at 'https://simonensemble.github.io/ppl/' was loaded over
HTTPS, but requested an insecure favicon 'http://simonensemble.github.io/assets/favicon.ico'.
This request has been blocked; the content must be served over HTTPS.
```

To fix this, change url in [_config.yml](https://github.com/SimonEnsemble/SimonEnsemble.github.io/blob/master/_config.yml) from,
```
url: http://simonensemble.github.io
```
to
```
url: https://simonensemble.github.io
```

**Comment by rhl-bthr** [comment]
While going through your repository for [#2](https://github.com/pro-panda/parchment/issues/2), I found a couple of issues,
 - [ ] Repository is not connected to the [original theme](https://github.com/pro-panda/parchment/issues). Fork the theme and make your changes over it so that you can easily copy patches from the theme.
 - [ ] Use `assets/` to store images and use them from there
 - [ ] You may remove files like `old_about.md`. It will always be stored in git in case you ever need it.
 - [ ] You need not comment out lines and add your own configurations, as in `_config.yml`. Again, git will preserve the history, provided that you have them in a previous commit
 - [ ] Remove files which you don't need. Eg: `resume.pdf`

Feel free to ask back in case any of it gets confusing to follow
